"""File for storing global variables.
"""
CONTROLLER_FREQUENCY = 120.0
FORCE_DAMPING = 0.03
K_P_FORCE = 0.03
K_P = 25.0
K_D = 1.8
K_ACC = 0.0

SPIDER_ORIGIN = 's'
LEG_ORIGIN = 'l'
GLOBAL_ORIGIN = 'g'

BEZIER_TRAJECTORY = 'bezier'
MINJERK_TRAJECTORY = 'minJerk'
