"""File for storing global variables.
"""
CONTROLLER_FREQUENCY = 120.0
FORCE_DAMPING = 0.001
K_P_FORCE = 0.04
K_P = 30.0
K_D = 2.2

SPIDER_ORIGIN = 's'
LEG_ORIGIN = 'l'
GLOBAL_ORIGIN = 'g'

BEZIER_TRAJECTORY = 'bezier'
MINJERK_TRAJECTORY = 'minJerk'
